export const FETCH_ACCESS_TOKEN_FAILED = 'FETCH_ACCESS_TOKEN_FAILED';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const GET_ATHLETE = 'GET_ATHLETE';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';
